apiVersion: v1
kind: Service
metadata:
  name: cinema-films
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8081
      targetPort: 8081
    - name: grpc
      port: 7081
      targetPort: 7081
  selector:
    app: cinema-films