apiVersion: v1
kind: Service
metadata:
  name: cinema-halls
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8083
      targetPort: 8083
    - name: grpc
      port: 7083
      targetPort: 7083
  selector:
    app: cinema-halls