apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-seances
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinema-seances
  template:
    metadata:
      labels:
        app: cinema-seances
    spec:
      containers:
        -
          image: myfirstmolly/seance
          name: cinema-seances
          ports:
            - containerPort: 8082
              name: rest
            - containerPort: 7082
              name: grpc
