apiVersion: v1
kind: Service
metadata:
  name: cinema-visitors
spec:
  type: ClusterIP
  ports:
    - name: "cinema-visitors"
      port: 8084
      targetPort: 8084
  selector:
    app: cinema-visitors